logging:
  level:
    root: info
    org.springframework.jdbc.core: trace

spring:
  liquibase:
    clear-checksums: false
  datasource:
    url: jdbc:postgresql://localhost:5433/food-diary
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: none
      default_batch_fetch_size: 50
      open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: diploma-food-diary

app:
  image:
    user:
      default: 307ce493-b254-4b2d-8ba4-d12c080d6651.png
  security:
    secret: 752cGOgRHqyr8ZyGFSQnxnruMuuj8oRaEvh2ne3QyAD
